### ISSUE TITLE
Error installation TracerPIN

### ISSUE THREAD

**Issue by 3AlaSploit** [SideChannelMarvels/Tracer#14]
Hi,

I'm on Ubuntu 16.04.2 64bits.
I did :
`sudo apt-get install --no-install-recommends wget make g++`
`sudo apt-get install --no-install-recommends libstdc++-4.9-dev libssl-dev libsqlite3-dev`
`sudo dpkg --add-architecture i386`
`sudo apt-get update`
`sudo apt-get install --no-install-recommends gcc-multilib g++-multilib`
`sudo apt-get install --no-install-recommends libstdc++-4.9-dev:i386 libssl-dev:i386 libsqlite3-dev:i386`

After that i was on 'https://software.intel.com/en-us/articles/pintool-downloads' to download the latest version of Pintool.
Next step:

`sudo mv pin-3.2-81205-gcc-linux/ /opt`
`export PIN_ROOT=/opt/pin-3.2-81205-gcc-linux`
`echo -e "\nexport PIN_ROOT=/opt/pin-3.2-81205-gcc-linux" >> ~/.bashrc`
And when i did : make 
I got this error :
![screenshot from 2017-04-26 15-11-29](https://cloud.githubusercontent.com/assets/2794716/25436160/c09c29ce-2a92-11e7-92be-f0f3e1ee446a.png)
 
How can I fix it please?

Thanks for your help.

**Comment by doegox** [comment]
Try using PIN 2.14, we don't support more recent versions yet.
Watch issue #9 for any progress.

**Comment by 3AlaSploit** [comment]
Thank you for your reply.
I installed version 2.14 but I get this error:
![screenshot from 2017-04-28 01-39-03](https://cloud.githubusercontent.com/assets/2794716/25508632/b2944aba-2bb3-11e7-89cc-21e64f62acd0.png)

Do you know why ? 
Thank you very much.

**Comment by doegox** [comment]
Sounds like you're not in multiarch environment.
You need to do sth like this:
```
dpkg --add-architecture i386
apt-get update
apt-get install gcc-multilib g++-multilib libsqlite3-dev:i386
```
See also the dockerfiles for a more complete view of the dependencies for all SideChannelMarvels tools:
* https://github.com/SideChannelMarvels/Orka/blob/master/marvelsbase/Dockerfile
* https://github.com/SideChannelMarvels/Orka/blob/master/marvelslatest/Dockerfile

**Comment by 3AlaSploit** [comment]
I have a multiarch environment.

I always have a mistake with the target 'ia32' when I do make.
![screenshot from 2017-05-04 20-26-01](https://cloud.githubusercontent.com/assets/2794716/25718981/4c83570c-3108-11e7-97ab-acae97351db3.png)

**Comment by gipi** [comment]
I had some problems compiling it (my system is a x86_64) but using ``make CXX=g++-4.9 intel64`` all worked fine.
