### ISSUE TITLE
Ease data inspection in tracegraph

### ISSUE THREAD

**Issue by protopyte** [SideChannelMarvels/Tracer#16]
Data inspection in tracegraph could be improved drastically with something like a magnetic pointer.

Right now, I have to zoom quite a lot to click on a point I am interested in and display its info. My mouse pointer seems to be physically right on top of it but somehow, I am clicking outside of it.

I suggest two different ways to address this, depending on what you feel is simpler:
- something like the picker parameter of a matplotlib plot (if within less than $picker pixels of a POI, it gets picked)
- something like a magnetic behaviour (if my mouse pointer gets close enough in pixels, it moves automatically to the POI)

Note that in both cases, I am reasoning in pixels, not coordinates. It feels like I'm clicking outside of the POIs right now because I am too far in terms of coordinates, meaning that the zoom level is not taken into account to give me more tolerance when I am zoomed out.

Thank you

**Comment by doegox** [comment]
One trick to ease dot picking is to increase temporarily their size (press + several times). Clicking anywhere within the enlarged dot will work.

**Comment by protopyte** [comment]
Thank you, that makes it way simpler. This shortcut would be a nice addition to those you already have in the README.md, I think.

You can close this issue, as far as I'm concerned.

**Comment by doegox** [comment]
Fixed in commit 0a40a8e
