### ISSUE TITLE
Tracer build fails in Orka

### ISSUE THREAD

**Issue by ikizhvatov** [SideChannelMarvels/Tracer#21]
The latest commit with MIPS32 seems to have broken the build, at least in the marvelslatest image. When rebuilding from scratch (and having rebuilt marvelsbase from scratch), I get:

```
Step 17/29 : WORKDIR "/root/Tracer/TracerGrind/texttrace"
 ---> 69d8a65d6548
Removing intermediate container f17b81e0b197
Step 18/29 : RUN make     && make install
 ---> Running in 299322bdbae3
gcc -O3 -c texttrace.c -o texttrace.o
texttrace.c: In function 'main':
texttrace.c:112:28: error: 'CS_MODE_MIPS32' undeclared (first use in this function)
                     mode = CS_MODE_MIPS32;
                            ^
texttrace.c:112:28: note: each undeclared identifier is reported only once for each function it appears in
make: *** [texttrace.o] Error 1
Makefile:14: recipe for target 'texttrace.o' failed
The command '/bin/sh -c make     && make install' returned a non-zero code: 2
```

**Comment by doegox** [comment]
Thanks Ilya
It's probably the right time to move Orka from Debian oldstable (jessie) to stable (stretch).
I'm testing it.

**Comment by doegox** [comment]
I updated Orka, as there were more breaks (Daredevil dep, Valgrind repo)
https://github.com/SideChannelMarvels/Orka/commit/39776f8c698c69d7caf1cc61d90d960cae52c08b

But this new one doesn't contain the compilation of PIN anymore.
Maybe we'll reintegrate it later once I figure out how to include decently a GCC 4.4.7 (or at least <5) in this Debian Stretch docker image...
