### ISSUE TITLE
[TraceGraph] Sqlite Performance issue - Zoom in and Out

### ISSUE THREAD

**Issue by rex2re** [SideChannelMarvels/Tracer#32]
```
tracergrind binary: 1.5 GB
Sqlitetrace Db: 5.67 GB
```
TraceGraph able to load the db in 5 - 10 min, but zoom in, zoom out and other option are loading very slow. any idea to fix it ?

**Comment by doegox** [comment]
It's a known limitation especially when the displayed area represents many data.
This could be improved maybe by sampling less data in these cases.
Pull requests are welcome.
